name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: pull the latest changes
        run: git -C /root/tetrakis pull
        
      - name: build the project
        run: dotnet build /root/tetrakis/Tetrakis
        
      - name: restart the service
        run: systemctl restart tetrakis
